spring.application.name=MultiUserShopList
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url =jdbc:postgresql://localhost:5432/ShopApp
spring.datasource.username=postgres
spring.datasource.password=1

